# -*- coding: utf-8 -*-
"""TrackA_AI_Manufacturing_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a9AJObSItUJKDhKWTLcpotfiR-9dzjoI
"""

import numpy as np
import pandas as pd

np.random.seed(42)

n = 4000

data = pd.DataFrame({
    "Temperature": np.random.normal(180, 10, n),
    "Pressure": np.random.normal(5, 1, n),
    "Hold_Time": np.random.normal(60, 10, n),
    "Machine_RPM": np.random.normal(1500, 200, n),
    "Machine_Load": np.random.uniform(50, 100, n),
    "Batch_Size": np.random.randint(500, 2000, n)
})

# Targets
data["Energy_Consumption"] = (
    0.05 * data["Temperature"] +
    0.1 * data["Machine_Load"] +
    0.002 * data["Machine_RPM"] +
    np.random.normal(0, 2, n)
)

data["Quality_Score"] = (
    100 -
    0.03 * data["Temperature"] -
    0.05 * data["Machine_Load"] +
    np.random.normal(0, 1, n)
)

data["Yield_Percentage"] = (
    85 +
    0.01 * data["Temperature"] -
    0.02 * data["Machine_Load"] +
    np.random.normal(0, 1, n)
)

data["Performance_Index"] = (
    75 +
    0.02 * data["Machine_RPM"] / 100 -
    0.01 * data["Hold_Time"] +
    np.random.normal(0, 1, n)
)

data.head()

from sklearn.model_selection import train_test_split
from sklearn.multioutput import MultiOutputRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score

X = data[["Temperature", "Pressure", "Hold_Time", "Machine_RPM", "Machine_Load", "Batch_Size"]]
y = data[["Energy_Consumption", "Quality_Score", "Yield_Percentage", "Performance_Index"]]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = MultiOutputRegressor(XGBRegressor())
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("R2 Score:", r2_score(y_test, y_pred))

import matplotlib.pyplot as plt

plt.figure()
plt.plot(data["Energy_Consumption"].values[:200])
plt.title("Energy Consumption Pattern (First 200 Batches)")
plt.xlabel("Batch")
plt.ylabel("Energy Consumption")
plt.show()

rolling_mean = data["Energy_Consumption"].rolling(window=50).mean()

plt.figure()
plt.plot(rolling_mean)
plt.title("Rolling Mean Energy Consumption (Drift Detection)")
plt.xlabel("Batch")
plt.ylabel("Rolling Energy Mean")
plt.show()

import seaborn as sns

plt.figure()
sns.heatmap(data.corr(), annot=True)
plt.title("Feature Correlation Matrix")
plt.show()

!pip install shap

import shap

explainer = shap.Explainer(model.estimators_[0])
shap_values = explainer(X_test)

shap.plots.beeswarm(shap_values)

### Energy Pattern Intelligence Insights

- High Machine Load increases energy consumption significantly.
- Temperature variations influence quality score.
- RPM variation affects performance index.
- Rolling energy drift can indicate maintenance need.

def predict_batch(temp, pressure, hold, rpm, load, batch_size):
    input_data = pd.DataFrame([[temp, pressure, hold, rpm, load, batch_size]],
                              columns=["Temperature", "Pressure", "Hold_Time",
                                       "Machine_RPM", "Machine_Load", "Batch_Size"])

    prediction = model.predict(input_data)

    return {
        "Predicted Energy": prediction[0][0],
        "Predicted Quality": prediction[0][1],
        "Predicted Yield": prediction[0][2],
        "Predicted Performance": prediction[0][3]
    }

predict_batch(185, 5.5, 60, 1600, 80, 1200)

def carbon_logic(energy_value):
    carbon_factor = 0.82  # example kg CO2 per kWh
    carbon_emission = energy_value * carbon_factor

    if carbon_emission > 120:
        recommendation = "Reduce Machine Load or RPM to meet carbon target."
    else:
        recommendation = "Within carbon limits."

    return carbon_emission, recommendation

result = predict_batch(185, 5.5, 60, 1600, 80, 1200)
carbon_logic(result["Predicted Energy"])

from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

targets = ["Energy", "Quality", "Yield", "Performance"]

for i in range(4):
    mae = mean_absolute_error(y_test.iloc[:, i], y_pred[:, i])
    rmse = np.sqrt(mean_squared_error(y_test.iloc[:, i], y_pred[:, i]))
    r2 = r2_score(y_test.iloc[:, i], y_pred[:, i])

    print(f"\nTarget: {targets[i]}")
    print("MAE:", round(mae, 3))
    print("RMSE:", round(rmse, 3))
    print("R2:", round(r2, 3))

from sklearn.model_selection import cross_val_score
from sklearn.multioutput import MultiOutputRegressor
from xgboost import XGBRegressor

cv_model = MultiOutputRegressor(XGBRegressor())

scores = cross_val_score(cv_model, X, y, cv=5, scoring='r2')

print("Cross-validation R2 scores:", scores)
print("Average CV R2:", scores.mean())

import joblib
joblib.dump(model, "multi_target_model.pkl")

def intelligent_batch_analysis(temp, pressure, hold, rpm, load, batch_size):

    result = predict_batch(temp, pressure, hold, rpm, load, batch_size)
    carbon_emission, recommendation = carbon_logic(result["Predicted Energy"])

    print("\n--- Batch Analysis Report ---")
    print("Predicted Energy:", round(result["Predicted Energy"], 2))
    print("Predicted Quality:", round(result["Predicted Quality"], 2))
    print("Predicted Yield:", round(result["Predicted Yield"], 2))
    print("Predicted Performance:", round(result["Predicted Performance"], 2))
    print("Estimated Carbon Emission:", round(carbon_emission, 2))
    print("Recommendation:", recommendation)

intelligent_batch_analysis(185, 5.5, 60, 1600, 80, 1200)

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

X_processed = pipeline.fit_transform(X)